import { createAction } from "@reduxjs/toolkit";
import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {
    SEARCH_SPARES: `${STATE_REDUCER_KEY}/SEARCH_SPARES`,
    SEARCH_SPARES_REQUEST: `${STATE_REDUCER_KEY}/SEARCH_SPARES_REQUEST`,
    SEARCH_SPARES_SUCCESS: `${STATE_REDUCER_KEY}/SEARCH_SPARES_SUCCESS`,
    SEARCH_SPARES_FAILURE: `${STATE_REDUCER_KEY}/SEARCH_SPARES_FAILURE`

};

export const searchSpare = createAction(ACTION_TYPES.SEARCH_SPARES);
