import { createAction } from "@reduxjs/toolkit";
import { STATE_REDUCER_KEY } from "./constants";

export const ACTION_TYPES = {
    SEARCH_VENDOR: `${STATE_REDUCER_KEY}/SEARCH_VENDOR`,
    SEARCH_VENDOR_REQUEST: `${STATE_REDUCER_KEY}/SEARCH_VENDOR_REQUEST`,
    SEARCH_VENDOR_SUCCESS: `${STATE_REDUCER_KEY}/SEARCH_VENDOR_SUCCESS`,
    SEARCH_VENDOR_FAILURE: `${STATE_REDUCER_KEY}/SEARCH_VENDOR_FAILURE`,

    SPEND_ANALYSIS_RESULT: `${STATE_REDUCER_KEY}/SPEND_ANALYSIS_RESULT`,
    SPEND_ANALYSIS_RESULT_REQUEST: `${STATE_REDUCER_KEY}/SPEND_ANALYSIS_RESULT_REQUEST`,
    SPEND_ANALYSIS_RESULT_SUCCESS: `${STATE_REDUCER_KEY}/SPEND_ANALYSIS_RESULT_SUCCESS`,
    SPEND_ANALYSIS_RESULT_FAILURE: `${STATE_REDUCER_KEY}/SPEND_ANALYSIS_RESULT_FAILURE`,

    TREND_ANALYSIS_RESULT: `${STATE_REDUCER_KEY}/TREND_ANALYSIS_RESULT`,
    TREND_ANALYSIS_RESULT_REQUEST: `${STATE_REDUCER_KEY}/TREND_ANALYSIS_RESULT_REQUEST`,
    TREND_ANALYSIS_RESULT_SUCCESS: `${STATE_REDUCER_KEY}/TREND_ANALYSIS_RESULT_SUCCESS`,
    TREND_ANALYSIS_RESULT_FAILURE: `${STATE_REDUCER_KEY}/TREND_ANALYSIS_RESULT_FAILURE`


};

export const searchVessel = createAction(ACTION_TYPES.SEARCH_VENDOR);
export const fetchSpendAnalysisResult = createAction(ACTION_TYPES.SPEND_ANALYSIS_RESULT);
export const fetchTrendAnalysisResult = createAction(ACTION_TYPES.TREND_ANALYSIS_RESULT);


